# Generated by Django 3.2.4 on 2021-06-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=50)),
                ('app_date', models.DateField()),
                ('app_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
